kind: Service
apiVersion: v1
metadata:
  name: phpserver
  labels:
    app: phpserver
spec:
  selector:
    app: phpserver
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpserver-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phpserver
        version: v1
    spec:
      containers:
        - name: phpserver
          image: yeedom/istio-demo
          imagePullPolicy: IfNotPresent
          env:
            - name: version
              value: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpserver-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phpserver
        version: v2
    spec:
      containers:
        - name: phpserver
          image: yeedom/istio-demo
          imagePullPolicy: IfNotPresent
          env:
            - name: version
              value: v2
